# Generated by Django 5.2.6 on 2025-10-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='평점을 입력해주세요', verbose_name='리뷰 평점')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='설명')),
                ('author', models.TextField(max_length=50, verbose_name='저자')),
            ],
        ),
    ]
